- name: Variables from Files
  hosts: localhost
  vars_files:
  - variables.yaml
  
  tasks:
  - name: Printing variables from file
    debug:
      msg: "We are learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"