- name: Testing Variables Precendence
  hosts: localhost
  vars:
    NAME: Mishima
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: USERNAME
    prompt: Please Enter your Username
    private: false

  tasks:
  - name: Printing the value of NAME for precedence checking..!
    vars:
      NAME: Heihachi
    debug:
      print: The value of NAME is {{NAME}}
      
# Precedence Flow : 

# 1.  Command Line Arguments
# 2.  Task Level Variables
# 3.  File Variables
# 4.  Prompt
# 5.  Play
# 6.  Inventory
# 7.  Roles