- name: Installing Packages
  hosts: mongodb
  become: true
  tasks:
  - name: Package Installing..
    yum:
      name: "{{item}}"
      state: installed
    # list of packages
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx