- name: Install catalogue service
  hosts: catalogue
  become: true
  tasks:
  - name: Setup NPM Source
    tags:
    - installation
    shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install NodeJs
    tags:
    - installation
    yum:
      name: nodejs
      state: installed   

  - name: Check whether user "Roboshop" is available
    tags:
    - installation
    command: id roboshop
    register: cmdOut
    ignore_errors: true

  - name: Print Command Output
    tags:
    - installation
    debug:
      msg: "Command Output : {{cmdOut}}"

  - name: Print Exit Status
    tags:
    - installation
    debug:
      msg: "Exit Status : {{cmdOut.rc}}"
  
  - when: cmdOut.rc != 0
    name: Create User Roboshop
    tags:
    - installation
    become: true
    user:
      name: roboshop

  - name: Check /app directory is available or not
    tags:
    - installation
    stat:
      path: /app
    register: directory

  - name: Print directory status
    tags:
    - installation
    debug:
      msg: "Directory Status : {{directory}}"

  - when: directory.stat.exists == False
    name: Create app directory if not availabe
    tags:
    - installation
    file:
      path: /app
      state: directory

  - name: Download Catalogue Artifacts
    tags:
    - deployment
    get_url:
      url:  https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  
  - name: Unzipping the Artifacts
    tags:
    - deployment
    unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
      
  - name: Change the directory to /app and install dependencies
    tags:
    - deployment
    command: npm install
    args:
      chdir: /app


  - name: copy catalogue service file to systemd
    tags:
    - installation
    copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service 

  - name: Reloading Daemon
    tags:
    - installation
    systemd:
      daemon_reload: true

  - name: Copy mongodb repo to yum.repos.d
    tags:
    - installation
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB
    tags:
    - installation
    yum:
      name: mongodb-org-shell
      state: installed
  
  - name: Loading data into MongoDB
    tags:
    - installation
    shell: mongo --host mongodb.bsebregistration.com < /app/schema/catalogue.js

  - name: Restarting Catalogue Service
    tags:
    - deployment
    service:
      name: catalogue
      state: restarted
      enabled: yes


      

