- name: Install catalogue service
  hosts: catalogue
  become: true
  tasks:
  - name: Setup NPM Source
    shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: Install NodeJs
    yum:
      name: nodejs
      state: installed

  - name: Check whether user "Roboshop" is available
    command: id roboshop
    register: cmdOut
    ignore_errors: true

  - name: Print Command Output
    debug:
      msg: "Command Output : {{cmdOut}}"
  - name: Print Exit Status
    debug:
      msg: "Exit Status : {{cmdOut.rc}}"
  
  - when: cmdOut.rc != 0
    name: Create User Roboshop
    become: true
    user:
      name: roboshop

  - name: Check /app directory is available or not
    stat:
      path: /app
    register: directory
  - name: Print directory status
    debug:
      msg: "Directory Status : {{directory}}"

  - when: directory.stat.exists == False
    name: Create app directory if not availabe
    file:
      path: /app
      state: directory

  - name: Download Catalogue Artifacts
    get_url:
      url:  https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  
  - name: Unzipping the Artifacts
    unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: Change the directory to /app and install dependencies
    command: npm install
    args:
      chdir: /app

  - name: copy catalogue service file to systemd
    copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Reloading Daemon
    systemd:
      daemon_reload: true

  - name: Copy mongodb repo to yum.repos.d
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install MongoDB
    yum:
      name: mongodb-org-shell
      state: installed
  
  - name: Loading data into MongoDB
    command: mongo --host mongodb.bsebregistration.com < /app/schema/catalogue.js

  - name: Restarting Catalogue Service
    service:
      name: catalouge
      state: restarted
      enabled: yes


      

