- name: Praparing RabbitMQ Component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: Configuring yum repo script provided by MQ Vendor
    shell: "{{item}}"
    loop:
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: Installing RabbitMQ
    yum:
      name: rabbitmq-server
      state: installed

  - name: Restarting RabbitMQ
    service:
      name: rabbitmq-server
      state: restarted
      enabled: true

  - name: Create RabbitMQ User
    shell: rabbitmqctl add_user roboshop roboshop123

  - name: Setting Up Permissions
    shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"